on:
  push:
    branches:
    - main
    - release/*
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu:latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
    - uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.google.com
      # Optional port (defaults to 465)
        port: 465
        account: examencloudsystemenilias@gmail.com
        password: MYSECRET
        sender: devellany
        from: examencloudsystemenilias@gmail.com
        to: examencloudsystemenilias@gmail.com
        subject: linesofcode.
        body: linesofcode.
      # Optional content type (defaults to text/plain)
        contentType: /tmp/linesofcode.txt
      # Optional attachment files (JSON type. require property 'path')
        attachments: '[{"/tmp/linesofcode.txt":"README.md"}]'

