on:
  push:
    branches:
    - main
    - release/*
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu:latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
        
  
    - uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.google.com
      # Optional port (defaults to 465)
        port: 465
        account: examencloudsystemenilias@gmail.com
        password: ${{secrets.MAIL_PASSWORD}}
        sender: devellany
        from: ${{secrets.MAIL_ADDRESS}}
        to: devellay@dico.me
        subject: mail title.
        body: your messages.
      # Optional content type (defaults to text/plain)
        contentType: text/plain
      # Optional attachment files (JSON type. require property 'path')
        attachments: '[{"path":"README.md"}]'

